### ISSUE TITLE
I have some questions about the configuration of the environment, can I ask you?

### ISSUE THREAD

**Issue by sbzd12138ctrl** [zjysteven/PrivayAttack_AT_FL#2]
Hello: Which version of the dataset was used in your paper? I have some questions about the configuration of the environment, can I ask you?

**Comment by zjysteven** [comment]
Feel free to directly post your question for better communication efficiency. Also what do you mean by "which version of the dataset was used"?

**Comment by sbzd12138ctrl** [comment]
Thanks for the reply Is there a version requirement for the .robustness library Why can't CUDA be used after I install it

**Comment by zjysteven** [comment]
No, the robustness library https://github.com/MadryLab/robustness hasn't been updated for years and I don't think it really has different versions. It shouldn't affect cuda in any ways though. Unfortunately I don't think I can help much with the issue you ran into (there could be many reasons; most likely related to your environment).

A potential workaround is that instead of installing the robustness library, you just copy the code in this file https://github.com/MadryLab/robustness/blob/master/robustness/attacker.py manually to somewhere and replace the line below to make the import.
https://github.com/zjysteven/PrivacyAttack_AT_FL/blob/222b9b94e7a4e685fd96edc567d8bfa543b721f6/inversion.py#L11C1-L11C46

**Comment by sbzd12138ctrl** [comment]
Thanks for the reply But I haven't solved my problem yet. I'll look into it again

**Comment by sbzd12138ctrl** [comment]
Hello, I've solved the problem with the environment, how should your project run, or what is the order in which the files run?

**Comment by zjysteven** [comment]
Please see the instruction in README https://github.com/zjysteven/PrivacyAttack_AT_FL#reproducing-experiments

**Comment by sbzd12138ctrl** [comment]
Can I simply run main.sh after setting up the dataset and changing the path to reproduce it? Why do I have many problems after following the requirements

**Comment by sbzd12138ctrl** [comment]
I followed your readme file to try to reproduce the result of your code, but it has not worked, can you help me see what went wrong?

**Comment by zjysteven** [comment]
First you need to let me know what exact problems you ran into, by showing the printed error or things like that. I might be able to take a look when I have chance.

**Comment by sbzd12138ctrl** [comment]
Running shows FileNotFoundError: [WinError 3] The system could not find the specified path. : '.. /data/ImageNet/traintest', but I've created the imagenet folder and have both train and val folders, and changed the path in the main.sh as well.

**Comment by zjysteven** [comment]
According to your current setup, the data folder should be structured like this
```
data
├── ImageNet
│   ├── train
│   ├── val
```
And you should pass `../data/ImageNet` to the `--inet-dir` argument in `main.sh`.

According to your error message it seems that you are passing `traintest` as the `--split` argument. Are you sure you have a `traintest` folder under `../data/ImageNet`? https://github.com/zjysteven/PrivacyAttack_AT_FL/blob/222b9b94e7a4e685fd96edc567d8bfa543b721f6/main.py#L65

**Comment by sbzd12138ctrl** [comment]
![2024-07-10_11-24-52](https://github.com/zjysteven/PrivacyAttack_AT_FL/assets/174400352/ce674745-93b0-46f8-9f54-1f52940cc984)

是这样设置吗？

**Comment by zjysteven** [comment]
两个问题。一是你data文件夹是和main.py在同一目录下的，但是`../data`是会在上一级目录去找，应该改成`./data/`。其次是你需要看下面源码，https://github.com/zjysteven/PrivacyAttack_AT_FL/blob/222b9b94e7a4e685fd96edc567d8bfa543b721f6/main.py#L65
具体的split，也就是`train`，`val`或者`test`是由`split`这个参数决定的，像上个回复说的一样对于`inet_dir`参数你只需要指定为`./data/ImageNet`。

以及我不知道你是否改了`main.py`里的代码，如果没改的话不清楚为什么在你截图的命令下会去找`../data/ImageNet/train\\test`这个路径。

这个bug是比较基本的路径问题，建议可以用chatgpt debug，比我们这么回复有效率得多。其次之前忘记提到，目前由于这个issue里 #1 提到的问题（我之前用的pretrained robust model的链接已经失效了，下载不了相应模型），main.py是无法跑通的。要解决的话需要找其他的pretrained robust model，以及可能要改代码。

**Comment by sbzd12138ctrl** [comment]
Thanks for the reply, I'm a beginner student and may not be very proficient yet, do you have a pre-trained model to share?

**Comment by zjysteven** [comment]
issue 1里面我放了个链接，但是那些pretrained模型不保证当前代码能跑。我后面可以找时间调一下，但是最快要等下周周中往后。

**Comment by sbzd12138ctrl** [comment]
Thank you very much for your reply. Looking forward to your adjusted code. May I ask if it is possible to add your contact information? I am currently a graduate student, and if it is inconvenient, please disregard this question.

**Comment by sbzd12138ctrl** [comment]
Hello, where did you put your modified code?

**Comment by zjysteven** [comment]
Unfortunately I didn't and wouldn't have bandwidth for this at least before mid August.

**Comment by sbzd12138ctrl** [comment]
Hello, have you had time to change the code recently?

**Comment by zjysteven** [comment]
No sorry still don't have bandwidth for that. I strongly recommend you trying to implement yourself based on the current implementation in the repo; it shouldn't be too difficult.

**Comment by sbzd12138ctrl** [comment]
Hello I tried to reproduce it many times according to the requirements of the readme without success, and then the code I wrote myself according to the logic in the paper was also unsuccessful, do you have any code that can be run directly to share.

**Comment by sbzd12138ctrl** [comment]
Hello, did it take 200 hours to sample 5000 adversarial samples of the ImageNet dataset in the first judgment in the main function?
